name: Cypress Tests and Slack Report

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      - name: Send report to Slack
        uses: rtCamp/action-slack-notify@v2
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack_message: |
            Cypress Test Report*

            - Passed: ${{ env.CYPRESS_PASSED }}
            - Failed: ${{ env.CYPRESS_FAILED }}
            - Skipped: ${{ env.CYPRESS_SKIPPED }}
            # Add any additional details or summaries here
