name: Cypress Tests and Slack Report
on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run demotest

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        with:
            env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        #    slack_message: |
        #     *Cypress Test Report*
        #     - Passed: ${{env.CYPRESS_PASSED}}
        #     - Failed: ${{env.CYPRESS_FAILED}}
        #     - Skipped: ${{env.CYPRESS_SKIPPED}}
    

       