name: Cypress Tests and Slack Report
on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Update dependencies
        run: npm update

      - name: Remove node_modules directory
        run: rm -rf node_modules

      - name: Reinstall dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          command: npm run demotest

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          slack_message: |
            Cypress Test Report*
            - Passed: ${{ env.CYPRESS_PASSED }}
            - Failed: ${{ env.CYPRESS_FAILED }}
            - Skipped: ${{ env.CYPRESS_SKIPPED }}
            # Add any additional details or summaries here
          status: ${{ job.status }}
          message: "Workflow ${{ github.workflow }} completed"
